In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
salary_url = "../Datasets/salary.csv"

In [3]:
datasets = pd.read_csv(salary_url)
datasets

       age  education.num  capital.gain  hours.per.week income
0       90              9             0              40  <=50K
1       82              9             0              18  <=50K
2       66             10             0              40  <=50K
3       54              4             0              40  <=50K
4       41             10             0              40  <=50K
...    ...            ...           ...             ...    ...
32556   22             10             0              40  <=50K
32557   27             12             0              38  <=50K
32558   40              9             0              40   >50K
32559   58              9             0              40  <=50K
32560   22              9             0              20  <=50K

[32561 rows x 5 columns]

In [139]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   education.num   32561 non-null  int64
 2   capital.gain    32561 non-null  int64
 3   hours.per.week  32561 non-null  int64
 4   income          32561 non-null  object
dtypes: int64(4), object(1)
memory usage: 1.2+ MB

In [140]:
datasets.columns

Index(['age', 'education.num', 'capital.gain', 'hours.per.week', 'income'], dtype='object')

In [141]:
datasets.head(10)

   age  education.num  capital.gain  hours.per.week income
0   90              9             0              40  <=50K
1   82              9             0              18  <=50K
2   66             10             0              40  <=50K
3   54              4             0              40  <=50K
4   41             10             0              40  <=50K
5   34              9             0              45  <=50K
6   38              6             0              40  <=50K
7   74             16             0              20   >50K
8   68              9             0              40  <=50K
9   41             10             0              60   >50K

In [142]:
datasets.iloc[100:201]

     age  education.num  capital.gain  hours.per.week income
100   50             15             0              60   >50K
101   46             16             0              55   >50K
102   53             13             0              40   >50K
103   50             15             0              30   >50K
104   41             15             0              55   >50K
..   ...            ...           ...             ...    ...
196   23             13             0              40   >50K
197   49              5             0              40   >50K
198   27             10             0              40   >50K
199   90              9             0              40  <=50K
200   68              9             0              30  <=50K

[101 rows x 5 columns]

In [143]:
datasets.iloc[100:201, 0:2]

     age  education.num
100   50             15
101   46             16
102   53             13
103   50             15
104   41             15
..   ...            ...
196   23             13
197   49              5
198   27             10
199   90              9
200   68              9

[101 rows x 2 columns]

In [144]:
datasets.isna().sum()

age               0
education.num     0
capital.gain      0
hours.per.week    0
income            0
dtype: int64

In [145]:
for col in datasets.columns:
  print(datasets[col].unique())

[90 82 66 54 41 34 38 74 68 45 52 32 51 46 57 22 37 29 61 21 33 49 23 59
 60 63 53 44 43 71 48 73 67 40 50 42 39 55 47 31 58 62 36 72 78 83 26 70
 27 35 81 65 25 28 56 69 20 30 24 64 75 19 77 80 18 17 76 79 88 84 85 86
 87]
[ 9 10  4  6 16 15 13 14  7 12 11  2  3  8  5  1]
[    0 99999 41310 34095 27828 25236 25124 22040 20051 18481 15831 15024
 15020 14344 14084 13550 11678 10605 10566 10520  9562  9386  8614  7978
  7896  7688  7443  7430  7298  6849  6767  6723  6514  6497  6418  6360
  6097  5721  5556  5455  5178  5060  5013  4934  4931  4865  4787  4687
  4650  4508  4416  4386  4101  4064  3942  3908  3887  3818  3781  3674
  3471  3464  3456  3432  3418  3411  3325  3273  3137  3103  2993  2977
  2964  2961  2936  2907  2885  2829  2653  2635  2597  2580  2538  2463
  2414  2407  2387  2354  2346  2329  2290  2228  2202  2176  2174  2105
  2062  2050  2036  2009  1848  1831  1797  1639  1506  1471  1455  1424
  1409  1173  1151  1111  1086  1055   991   914   594   401   114]
[40 18 45 20 60 35 55 76 50 42 25 32 90 48 15 70 52 72 39  6 65 12 80 67
 99 30 75 26 36 10 84 38 62 44  8 28 59  5 24 57 34 37 46 56 41 98 43 63
  1 47 68 54  2 16  9  3  4 33 23 22 64 51 19 58 53 96 66 21  7 13 27 11
 14 77 31 78 49 17 85 87 88 73 89 97 94 29 82 86 91 81 92 61 74 95]
['<=50K' '>50K']

In [146]:
datasets.rename(columns= {
    'age': 'Age', 'education.num': 'Education', 'capital.gain': 'Capital', 'hours.per.week': 'Hours', 'income': 'Income'
    },
    inplace= True
)

In [147]:
datasets.columns

Index(['Age', 'Education', 'Capital', 'Hours', 'Income'], dtype='object')

In [148]:
datasets['Income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [149]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y = datasets['Income']
datasets['Income'] = label.fit_transform(y)
label.classes_

array(['<=50K', '>50K'], dtype=object)

In [150]:
datasets['Income'].unique()

array([0, 1])

In [151]:
x = datasets.iloc[:,:-1].values
x

array([[90,  9,  0, 40],
       [82,  9,  0, 18],
       [66, 10,  0, 40],
       ...,
       [40,  9,  0, 40],
       [58,  9,  0, 40],
       [22,  9,  0, 20]])

In [152]:
y = datasets.iloc[:,-1].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [153]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 9)

In [154]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((26048, 4), (6513, 4), (26048,), (6513,))

In [155]:
datasets['Age'].min()

17

In [156]:
datasets.Age.max()

90

In [157]:
datasets.min()

Age          17
Education     1
Capital       0
Hours         1
Income        0
dtype: int64

In [158]:
datasets.max()

Age             90
Education       16
Capital      99999
Hours           99
Income           1
dtype: int64

In [159]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(X_train)
x_test = scaler.transform(X_test)

In [160]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 50)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [161]:
y_pred = knn.predict(x_test)

# Evaluate
from sklearn.metrics import accuracy_score, confusion_matrix
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)*100}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")

Accuracy Score: 82.11269768155995
Confusion Matrix:
[[4685  262]
 [ 903  663]]

In [162]:
datasets['Age'].unique()

array([90, 82, 66, 54, 41, 34, 38, 74, 68, 45, 52, 32, 51, 46, 57, 22, 37,
       29, 61, 21, 33, 49, 23, 59, 60, 63, 53, 44, 43, 71, 48, 73, 67, 40,
       50, 42, 39, 55, 47, 31, 58, 62, 36, 72, 78, 83, 26, 70, 27, 35, 81,
       65, 25, 28, 56, 69, 20, 30, 24, 64, 75, 19, 77, 80, 18, 17, 76, 79,
       88, 84, 85, 86, 87])

In [163]:
datasets['Education'].unique()

array([ 9, 10,  4,  6, 16, 15, 13, 14,  7, 12, 11,  2,  3,  8,  5,  1])

In [164]:
datasets['Capital'].unique()

array([    0, 99999, 41310, 34095, 27828, 25236, 25124, 22040, 20051,
       18481, 15831, 15024, 15020, 14344, 14084, 13550, 11678, 10605,
       10566, 10520,  9562,  9386,  8614,  7978,  7896,  7688,  7443,
        7430,  7298,  6849,  6767,  6723,  6514,  6497,  6418,  6360,
        6097,  5721,  5556,  5455,  5178,  5060,  5013,  4934,  4931,
        4865,  4787,  4687,  4650,  4508,  4416,  4386,  4101,  4064,
        3942,  3908,  3887,  3818,  3781,  3674,  3471,  3464,  3456,
        3432,  3418,  3411,  3325,  3273,  3137,  3103,  2993,  2977,
        2964,  2961,  2936,  2907,  2885,  2829,  2653,  2635,  2597,
        2580,  2538,  2463,  2414,  2407,  2387,  2354,  2346,  2329,
        2290,  2228,  2202,  2176,  2174,  2105,  2062,  2050,  2036,
        2009,  1848,  1831,  1797,  1639,  1506,  1471,  1455,  1424,
        1409,  1173,  1151,  1111,  1086,  1055,   991,   914,   594,
         401,   114])

In [165]:
datasets['Hours'].unique()

array([40, 18, 45, 20, 60, 35, 55, 76, 50, 42, 25, 32, 90, 48, 15, 70, 52,
       72, 39,  6, 65, 12, 80, 67, 99, 30, 75, 26, 36, 10, 84, 38, 62, 44,
        8, 28, 59,  5, 24, 57, 34, 37, 46, 56, 41, 98, 43, 63,  1, 47, 68,
       54,  2, 16,  9,  3,  4, 33, 23, 22, 64, 51, 19, 58, 53, 96, 66, 21,
        7, 13, 27, 11, 14, 77, 31, 78, 49, 17, 85, 87, 88, 73, 89, 97, 94,
       29, 82, 86, 91, 81, 92, 61, 74, 95])

In [166]:
Age = int(input("Enter new Enployee's Age: "))
Education = int(input("Enter new Employee's Education: "))
Capital = int(input("Enter new Employee's Capital Gain: "))
Hours = int(input("Enter new Employee's working hours: "))
newEmp = [[Age, Education, Capital, Hours]]
result = knn.predict(scaler.transform(newEmp))
print(result)

Enter new Enployee's Age: 22
Enter new Employee's Education: 13
Enter new Employee's Capital Gain: 1000
Enter new Employee's working hours: 40
[0]

In [167]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}")
print()
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)*100}")

Confusion Matrix:
[[4685  262]
 [ 903  663]]

Accuracy Score: 82.11269768155995

In [4]:
users_url = "../Datasets/users.csv"

In [5]:
dataset = pd.read_csv(users_url)

In [6]:
dataset

     User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   12            19000          0
1   15810944    Male   11            20000          0
2   15668575  Female    1            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   10            76000          0
..       ...     ...  ...              ...        ...
94  15786993  Female   45            83000          0
95  15709441  Female   35            44000          0
96  15710257  Female    4            25000          0
97  15582492    Male    5           123000          1
98  15575694    Male   35            73000          0

[99 rows x 5 columns]

In [171]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          99 non-null     int64
 1   Gender           99 non-null     object
 2   Age              99 non-null     int64
 3   EstimatedSalary  99 non-null     int64
 4   Purchased        99 non-null     int64
dtypes: int64(4), object(1)
memory usage: 4.0+ KB

In [173]:
dataset.rename(columns= {'User ID': 'UserID'}, inplace= True)

In [174]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UserID           99 non-null     int64
 1   Gender           99 non-null     object
 2   Age              99 non-null     int64
 3   EstimatedSalary  99 non-null     int64
 4   Purchased        99 non-null     int64
dtypes: int64(4), object(1)
memory usage: 4.0+ KB

In [179]:
dataset.head()

     UserID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   12            19000          0
1  15810944    Male   11            20000          0
2  15668575  Female    1            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   10            76000          0

In [180]:
dataset.isna().sum()

UserID             0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [181]:
dataset['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [187]:
X = dataset.iloc[:, 2:-1]
Y = dataset.iloc[:, -1]

In [190]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size= 0.2, random_state= 22)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((79, 2), (20, 2), (79,), (20,))

In [191]:
scaler = StandardScaler()
x_train = scaler.fit_transform(X_train)
x_test = scaler.transform(X_test)

In [196]:
from sklearn.svm import SVC
classifier = SVC(kernel= 'linear', random_state= 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [198]:
print(accuracy_score(y_test, y_pred) * 100)

85.0

In [199]:
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")

Confusion Matrix:
[[17  0]
 [ 3  0]]